language: python

python:
    - "2.7"

before_install:
    - sudo apt-get install libtidy-dev

install:
    - pip install -r requirements.txt

script:
    - py.test tests

branches:
    only:
        - master
